import { Pet, MapMarker } from '../types';

import shibaImg from '../assets/pets/shiba.avif';
import pomeranianImg from '../assets/pets/pomeranian.webp';
import malteseImg from '../assets/pets/maltese.jpeg';
import jackRussellImg from '../assets/pets/jack-russell.jpeg';
import chihuahuaWhiteImg from '../assets/pets/chihuahua-white.jpg';
import labBrownImg from '../assets/pets/lab-brown-puppy.jpg';
import labBlackImg from '../assets/pets/lab-black-puppy.jpg';
import bichonImg from '../assets/pets/bichon.jpg';
import yorkieImg from '../assets/pets/yorkie.jpg';
import chihuahuaTanImg from '../assets/pets/chihuahua-tan.jpg';

export const mockPets: Pet[] = [
  {
    id: '1',
    name: 'Buddy',
    breed: 'Golden Retriever',
    age: '2 yrs',
    gender: 'Male',
    distance: '3 mi',
    distanceMi: 3,
    size: 'Large',
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1552053831-71594a27632d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
    ],
    tags: ['Playful', 'Friendly', 'High Energy'],
    personality: ['Playful', 'Friendly', 'Energetic'],
    description: 'Buddy is an energetic ball of sunshine! He loves playing fetch at Green Lake, long walks along the Burke-Gilman Trail, and cuddles after a rainy Seattle day.',
    location: 'Capitol Hill, Seattle',
    ownerName: 'Sarah Jenkins',
    ownerImage: 'https://i.pravatar.cc/150?u=sarah',
    status: 'Available',
    activityLevel: 90,
    sociability: 95,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '2',
    name: 'Luna',
    breed: 'Husky Mix',
    age: '1 yr',
    gender: 'Female',
    distance: '8 mi',
    distanceMi: 8,
    size: 'Large',
    image: 'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1605568427561-40dd23c2acea?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Vocal', 'Smart', 'Escape Artist'],
    personality: ['Energetic', 'Playful'],
    description: 'Luna is a beautiful Husky mix with a big personality. She loves to howl at the ferries from Alki Beach and run through Discovery Park trails.',
    location: 'Ballard, Seattle',
    status: 'Available',
    activityLevel: 95,
    sociability: 70,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '3',
    name: 'Milo',
    breed: 'Tabby Cat',
    age: '3 yrs',
    gender: 'Male',
    distance: '12 mi',
    distanceMi: 12,
    size: 'Small',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Independent', 'Curious', 'Window Watcher'],
    personality: ['Calm', 'Friendly'],
    description: 'Milo is a curious explorer who loves watching the rain from the windowsill. He is independent but enjoys evening lap time while you binge Netflix.',
    location: 'Fremont, Seattle',
    status: 'Available',
    activityLevel: 40,
    sociability: 55,
    health: { vaccinated: true, neutered: true, dewormed: false }
  },
  {
    id: '4',
    name: 'Bella',
    breed: 'Beagle',
    age: '5 mos',
    gender: 'Female',
    distance: '18 mi',
    distanceMi: 18,
    size: 'Medium',
    image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Gentle', 'Quiet', 'Puppy'],
    personality: ['Calm', 'Friendly'],
    description: 'A sweet little soul looking for a patient owner. Bella is a bit shy at first but warms up quickly. She loves sniffing every leaf at Marymoor Park.',
    location: 'Bellevue, WA',
    status: 'Available',
    activityLevel: 50,
    sociability: 65,
    health: { vaccinated: true, neutered: false, dewormed: true }
  },
  {
    id: '5',
    name: 'Rocky',
    breed: 'Pug',
    age: '4 yrs',
    gender: 'Male',
    distance: '5 mi',
    distanceMi: 5,
    size: 'Small',
    image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1517849845537-4d257902454a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Chill', 'Apartment Friendly', 'Foodie'],
    personality: ['Calm'],
    description: 'Rocky is a couch potato king. Ideal for apartment living in the city. He snores a little but it adds to his charm. Favorite spot: Pike Place Market treats.',
    location: 'Downtown Seattle',
    status: 'Available',
    activityLevel: 20,
    sociability: 80,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '6',
    name: 'Daisy',
    breed: 'Corgi',
    age: '2 yrs',
    gender: 'Female',
    distance: '10 mi',
    distanceMi: 10,
    size: 'Medium',
    image: 'https://images.unsplash.com/photo-1612536057832-2ff7ead58194?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1612536057832-2ff7ead58194?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Herding', 'Fluffy Butt', 'Photogenic'],
    personality: ['Playful', 'Energetic', 'Friendly'],
    description: 'Daisy is a sassy Corgi who rules the house. She loves herding other dogs at Magnuson Park and posing in front of the Fremont Troll.',
    location: 'Wallingford, Seattle',
    status: 'Available',
    activityLevel: 75,
    sociability: 90,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '7',
    name: 'Max',
    breed: 'German Shepherd',
    age: '3 yrs',
    gender: 'Male',
    distance: '22 mi',
    distanceMi: 22,
    size: 'Large',
    image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Loyal', 'Protective', 'Trained'],
    personality: ['Calm', 'Friendly'],
    description: 'Max is a well-trained and loyal companion. Great with kids and loves structured play at Redmond\'s off-leash parks. Knows 15+ commands.',
    location: 'Redmond, WA',
    status: 'Available',
    activityLevel: 70,
    sociability: 60,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '8',
    name: 'Coco',
    breed: 'French Bulldog',
    age: '1 yr',
    gender: 'Female',
    distance: '6 mi',
    distanceMi: 6,
    size: 'Small',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Cuddly', 'Snorer', 'Fashionista'],
    personality: ['Calm', 'Friendly'],
    description: 'Coco is a tiny diva who loves wearing sweaters on rainy Seattle days and napping at dog-friendly cafes in Queen Anne.',
    location: 'Queen Anne, Seattle',
    status: 'Available',
    activityLevel: 25,
    sociability: 85,
    health: { vaccinated: true, neutered: false, dewormed: true }
  },
  {
    id: '9',
    name: 'Kuma',
    breed: 'Shiba Inu',
    age: '2 yrs',
    gender: 'Male',
    distance: '75 mi',
    distanceMi: 75,
    size: 'Medium',
    image: shibaImg,
    images: [shibaImg],
    tags: ['Sassy', 'Independent', 'Dramatic'],
    personality: ['Calm', 'Playful'],
    description: 'Kuma is a classic Shiba with the signature attitude. He gives the best side-eye in the Pacific Northwest and loves hiking at Mt. Rainier on weekends.',
    location: 'Olympia, WA',
    ownerName: 'Yuki Tanaka',
    ownerImage: 'https://i.pravatar.cc/150?u=yuki',
    status: 'Available',
    activityLevel: 60,
    sociability: 35,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '10',
    name: 'Snowball',
    breed: 'Pomeranian',
    age: '3 yrs',
    gender: 'Female',
    distance: '15 mi',
    distanceMi: 15,
    size: 'Small',
    image: pomeranianImg,
    images: [pomeranianImg],
    tags: ['Fluffy', 'Sunset Lover', 'Photogenic'],
    personality: ['Playful', 'Friendly'],
    description: 'Snowball is a cloud of pure joy. She loves sunset walks along Golden Gardens Beach and always draws a crowd with her fluffy white coat.',
    location: 'Kirkland, WA',
    ownerName: 'Emily Chen',
    ownerImage: 'https://i.pravatar.cc/150?u=emily',
    status: 'Available',
    activityLevel: 55,
    sociability: 92,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '11',
    name: 'Mochi',
    breed: 'Maltese',
    age: '8 mos',
    gender: 'Female',
    distance: '4 mi',
    distanceMi: 4,
    size: 'Small',
    image: malteseImg,
    images: [malteseImg],
    tags: ['Tiny', 'Adorable', 'Lap Dog'],
    personality: ['Calm', 'Friendly'],
    description: 'Mochi is the tiniest fluffball you will ever meet. She fits in a tote bag and loves being carried around Pike Place Market. Expert cuddler and treat connoisseur.',
    location: 'Capitol Hill, Seattle',
    ownerName: 'Lisa Park',
    ownerImage: 'https://i.pravatar.cc/150?u=lisa',
    status: 'Available',
    activityLevel: 15,
    sociability: 88,
    health: { vaccinated: true, neutered: false, dewormed: true }
  },
  {
    id: '12',
    name: 'Cooper',
    breed: 'Jack Russell Terrier',
    age: '6 mos',
    gender: 'Male',
    distance: '9 mi',
    distanceMi: 9,
    size: 'Small',
    image: jackRussellImg,
    images: [jackRussellImg],
    tags: ['Puppy', 'Zoomer', 'Adventurer'],
    personality: ['Playful', 'Energetic'],
    description: 'Cooper is a tiny rocket with boundless energy. He can jump three times his height and loves chasing squirrels at Volunteer Park. Always ready for the next adventure.',
    location: 'University District, Seattle',
    ownerName: 'Jake Morrison',
    ownerImage: 'https://i.pravatar.cc/150?u=jake',
    status: 'Available',
    activityLevel: 98,
    sociability: 82,
    health: { vaccinated: true, neutered: false, dewormed: true }
  },
  {
    id: '13',
    name: 'Peanut',
    breed: 'Chihuahua',
    age: '3 yrs',
    gender: 'Male',
    distance: '7 mi',
    distanceMi: 7,
    size: 'Small',
    image: chihuahuaWhiteImg,
    images: [chihuahuaWhiteImg],
    tags: ['Fearless', 'Harness Lover', 'Compact'],
    personality: ['Calm', 'Friendly'],
    description: 'Peanut may be small but he has the confidence of a Great Dane. He loves strutting around Green Lake in his black harness and supervising everyone at the dog park.',
    location: 'Green Lake, Seattle',
    ownerName: 'Maria Lopez',
    ownerImage: 'https://i.pravatar.cc/150?u=maria',
    status: 'Available',
    activityLevel: 35,
    sociability: 50,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '14',
    name: 'Cocoa',
    breed: 'Chocolate Lab',
    age: '4 mos',
    gender: 'Male',
    distance: '20 mi',
    distanceMi: 20,
    size: 'Large',
    image: labBrownImg,
    images: [labBrownImg],
    tags: ['Puppy', 'Smiley', 'Mouthy'],
    personality: ['Playful', 'Energetic', 'Friendly'],
    description: 'Cocoa is a happy-go-lucky chocolate Lab puppy with the biggest smile in the Pacific Northwest. He loves splashing in puddles at Marymoor Park and chewing on everything he finds.',
    location: 'Issaquah, WA',
    ownerName: 'Tom Baker',
    ownerImage: 'https://i.pravatar.cc/150?u=tom',
    status: 'Available',
    activityLevel: 85,
    sociability: 95,
    health: { vaccinated: true, neutered: false, dewormed: true }
  },
  {
    id: '15',
    name: 'Shadow',
    breed: 'Black Labrador',
    age: '3 mos',
    gender: 'Male',
    distance: '55 mi',
    distanceMi: 55,
    size: 'Large',
    image: labBlackImg,
    images: [labBlackImg],
    tags: ['Puppy', 'Runner', 'Teal Collar'],
    personality: ['Playful', 'Energetic'],
    description: 'Shadow is a bold little black Lab puppy who already loves running laps around the yard. Born near the foothills of the Cascades, he is destined for trail adventures and lake swims.',
    location: 'Ellensburg, WA',
    ownerName: 'Chris Palmer',
    ownerImage: 'https://i.pravatar.cc/150?u=chris',
    status: 'Available',
    activityLevel: 92,
    sociability: 78,
    health: { vaccinated: true, neutered: false, dewormed: false }
  },
  {
    id: '16',
    name: 'Biscuit',
    breed: 'Bichon Frise',
    age: '2 yrs',
    gender: 'Male',
    distance: '11 mi',
    distanceMi: 11,
    size: 'Small',
    image: bichonImg,
    images: [bichonImg],
    tags: ['Happy', 'Hypoallergenic', 'Fluffy Cloud'],
    personality: ['Playful', 'Friendly'],
    description: 'Biscuit is the happiest dog you will ever meet — that tongue is always out and that tail is always wagging. Great for allergy sufferers and perfect for apartment life in the city.',
    location: 'Mercer Island, WA',
    ownerName: 'Rachel Kim',
    ownerImage: 'https://i.pravatar.cc/150?u=rachel',
    status: 'Available',
    activityLevel: 45,
    sociability: 96,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '17',
    name: 'Ginger',
    breed: 'Yorkshire Terrier',
    age: '4 yrs',
    gender: 'Female',
    distance: '14 mi',
    distanceMi: 14,
    size: 'Small',
    image: yorkieImg,
    images: [yorkieImg],
    tags: ['Glamorous', 'Sunset Queen', 'Brave'],
    personality: ['Playful', 'Energetic'],
    description: 'Ginger is a feisty little Yorkie who loves golden hour photo sessions at Discovery Park. Do not let her size fool you — she will chase any dog twice her size and look fabulous doing it.',
    location: 'Magnolia, Seattle',
    ownerName: 'Sophie Wright',
    ownerImage: 'https://i.pravatar.cc/150?u=sophie',
    status: 'Available',
    activityLevel: 65,
    sociability: 72,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '18',
    name: 'Pepper',
    breed: 'Chihuahua',
    age: '5 yrs',
    gender: 'Female',
    distance: '3 mi',
    distanceMi: 3,
    size: 'Small',
    image: chihuahuaTanImg,
    images: [chihuahuaTanImg],
    tags: ['Sassy', 'Pink Harness', 'Loyal'],
    personality: ['Calm', 'Friendly'],
    description: 'Pepper is a spicy little Chihuahua with attitude to spare. She is fiercely loyal to her owner and loves warm laps, sunny patios in Ballard, and giving strangers the stink eye.',
    location: 'Ballard, Seattle',
    ownerName: 'Nina Hernandez',
    ownerImage: 'https://i.pravatar.cc/150?u=nina',
    status: 'Available',
    activityLevel: 30,
    sociability: 40,
    health: { vaccinated: true, neutered: true, dewormed: true }
  }
];

export const mockMapMarkers: MapMarker[] = [
  {
    id: 'm1',
    lat: 47.6456,
    lng: -122.3344,
    type: 'lost',
    petName: 'Max',
    description: 'Lost near Gas Works Park. Wearing red collar. Very friendly, responds to name.',
    timeAgo: '2h ago',
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'm2',
    lat: 47.6505,
    lng: -122.3509,
    type: 'stray',
    description: 'Spotted running near Aurora Bridge. Medium brown dog, no collar.',
    timeAgo: '15m ago',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'm3',
    lat: 47.6133,
    lng: -122.3445,
    type: 'stray',
    description: 'Small kitten hiding under a car in Belltown. Grey tabby, looks scared.',
    timeAgo: '1d ago',
    image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'm4',
    lat: 47.6280,
    lng: -122.3218,
    type: 'lost',
    petName: 'Bella',
    description: 'Lost in Capitol Hill near Volunteer Park. White Maltese, wearing pink bow. Please call if seen!',
    timeAgo: '5h ago',
    image: 'https://images.unsplash.com/photo-1587015566802-46ad946db660?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'm5',
    lat: 47.6688,
    lng: -122.3840,
    type: 'stray',
    description: 'Large black dog spotted near Ballard Locks. Appears well-fed, possibly lost.',
    timeAgo: '30m ago',
    image: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'm6',
    lat: 47.6062,
    lng: -122.3321,
    type: 'lost',
    petName: 'Oliver',
    description: 'Orange tabby cat missing from Pioneer Square area. Indoor cat, very shy. Has microchip.',
    timeAgo: '1d ago',
    image: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
  }
];
