import { Pet, MapMarker } from '../types';

export const mockPets: Pet[] = [
  {
    id: '1',
    name: 'Buddy',
    breed: 'Golden Retriever',
    age: '2 yrs',
    gender: 'Male',
    distance: '2.5 km',
    distanceKm: 2.5,
    size: 'Large',
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1552053831-71594a27632d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
    ],
    tags: ['Playful', 'Friendly', 'High Energy'],
    personality: ['Playful', 'Friendly', 'Energetic'],
    description: 'Buddy is an energetic ball of sunshine! He loves playing fetch, long walks on the beach, and cuddles. Looking for a playdate partner who can keep up!',
    location: 'San Francisco, CA',
    ownerName: 'Sarah Jenkins',
    ownerImage: 'https://i.pravatar.cc/150?u=sarah',
    status: 'Available',
    activityLevel: 90,
    sociability: 95,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '2',
    name: 'Luna',
    breed: 'Husky Mix',
    age: '1 yr',
    gender: 'Female',
    distance: '5 km',
    distanceKm: 5,
    size: 'Large',
    image: 'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1605568427561-40dd23c2acea?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Vocal', 'Smart', 'Escape Artist'],
    personality: ['Energetic', 'Playful'],
    description: 'Luna is a beautiful Husky mix with a lot of personality. She loves to sing, run, and explore new trails.',
    location: 'Oakland, CA',
    status: 'Available',
    activityLevel: 95,
    sociability: 70,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '3',
    name: 'Milo',
    breed: 'Tabby Cat',
    age: '3 yrs',
    gender: 'Male',
    distance: '10 km',
    distanceKm: 10,
    size: 'Small',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Independent', 'Curious', 'Chill'],
    personality: ['Calm', 'Friendly'],
    description: 'Milo is a curious explorer who loves high places. He is independent but enjoys evening lap time.',
    location: 'Fremont, CA',
    status: 'Available',
    activityLevel: 40,
    sociability: 55,
    health: { vaccinated: true, neutered: true, dewormed: false }
  },
  {
    id: '4',
    name: 'Bella',
    breed: 'Beagle',
    age: '5 mos',
    gender: 'Female',
    distance: '12 km',
    distanceKm: 12,
    size: 'Medium',
    image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Gentle', 'Quiet', 'Puppy'],
    personality: ['Calm', 'Friendly'],
    description: 'A sweet little soul looking for a patient owner. Bella is a bit shy at first but warms up quickly.',
    location: 'San Jose, CA',
    status: 'Available',
    activityLevel: 50,
    sociability: 65,
    health: { vaccinated: true, neutered: false, dewormed: true }
  },
  {
    id: '5',
    name: 'Rocky',
    breed: 'Pug',
    age: '4 yrs',
    gender: 'Male',
    distance: '3 km',
    distanceKm: 3,
    size: 'Small',
    image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1517849845537-4d257902454a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Chill', 'Apartment Friendly', 'Foodie'],
    personality: ['Calm'],
    description: 'Rocky is a couch potato king. Ideal for apartment living. He snores a little but it adds to his charm.',
    location: 'San Francisco, CA',
    status: 'Available',
    activityLevel: 20,
    sociability: 80,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '6',
    name: 'Daisy',
    breed: 'Corgi',
    age: '2 yrs',
    gender: 'Female',
    distance: '8 km',
    distanceKm: 8,
    size: 'Medium',
    image: 'https://images.unsplash.com/photo-1612536057832-2ff7ead58194?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1612536057832-2ff7ead58194?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Herding', 'Fluffy Butt', 'Photogenic'],
    personality: ['Playful', 'Energetic', 'Friendly'],
    description: 'Daisy is a sassy Corgi who rules the house. She loves herding other dogs at the park and posing for photos.',
    location: 'Berkeley, CA',
    status: 'Available',
    activityLevel: 75,
    sociability: 90,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '7',
    name: 'Max',
    breed: 'German Shepherd',
    age: '3 yrs',
    gender: 'Male',
    distance: '15 km',
    distanceKm: 15,
    size: 'Large',
    image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Loyal', 'Protective', 'Trained'],
    personality: ['Calm', 'Friendly'],
    description: 'Max is a well-trained and loyal companion. Great with kids and loves structured play. Knows 15+ commands.',
    location: 'Palo Alto, CA',
    status: 'Available',
    activityLevel: 70,
    sociability: 60,
    health: { vaccinated: true, neutered: true, dewormed: true }
  },
  {
    id: '8',
    name: 'Coco',
    breed: 'French Bulldog',
    age: '1 yr',
    gender: 'Female',
    distance: '4 km',
    distanceKm: 4,
    size: 'Small',
    image: 'https://images.unsplash.com/photo-1583337130417-13104dec14a3?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1583337130417-13104dec14a3?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'],
    tags: ['Cuddly', 'Snorer', 'Fashionista'],
    personality: ['Calm', 'Friendly'],
    description: 'Coco is a tiny diva who loves wearing sweaters and napping on soft blankets. Perfect lap dog.',
    location: 'San Francisco, CA',
    status: 'Available',
    activityLevel: 25,
    sociability: 85,
    health: { vaccinated: true, neutered: false, dewormed: true }
  }
];

export const mockMapMarkers: MapMarker[] = [
  {
    id: 'm1',
    lat: 35,
    lng: 45,
    type: 'lost',
    petName: 'Max',
    description: 'Lost near Central Park. Wearing red collar.',
    timeAgo: '2h ago',
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'm2',
    lat: 60,
    lng: 70,
    type: 'stray',
    description: 'Spotted running near the highway.',
    timeAgo: '15m ago',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'm3',
    lat: 25,
    lng: 20,
    type: 'stray',
    description: 'Small kitten hiding under a car.',
    timeAgo: '1d ago',
    image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
  }
];
